// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// srrmlr_one
Rcpp::List srrmlr_one(arma::dmat& X, arma::dmat& Y, arma::uword s, arma::uword r, double e_in, double e_out);
RcppExport SEXP _SRRMLR_srrmlr_one(SEXP XSEXP, SEXP YSEXP, SEXP sSEXP, SEXP rSEXP, SEXP e_inSEXP, SEXP e_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type e_in(e_inSEXP);
    Rcpp::traits::input_parameter< double >::type e_out(e_outSEXP);
    rcpp_result_gen = Rcpp::wrap(srrmlr_one(X, Y, s, r, e_in, e_out));
    return rcpp_result_gen;
END_RCPP
}
// srrmlr_simu
Rcpp::List srrmlr_simu(arma::dmat& train_X, arma::dmat& train_Y, arma::dmat& val_X, arma::dmat& val_Y, arma::dmat& test_X, arma::dmat& test_Y, arma::uvec& s_list, arma::uvec& r_list, arma::dmat& C_true, arma::uword s_true, arma::uword r_true);
RcppExport SEXP _SRRMLR_srrmlr_simu(SEXP train_XSEXP, SEXP train_YSEXP, SEXP val_XSEXP, SEXP val_YSEXP, SEXP test_XSEXP, SEXP test_YSEXP, SEXP s_listSEXP, SEXP r_listSEXP, SEXP C_trueSEXP, SEXP s_trueSEXP, SEXP r_trueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat& >::type train_X(train_XSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type train_Y(train_YSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type val_X(val_XSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type val_Y(val_YSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type test_X(test_XSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type test_Y(test_YSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type s_list(s_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type r_list(r_listSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type C_true(C_trueSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type s_true(s_trueSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type r_true(r_trueSEXP);
    rcpp_result_gen = Rcpp::wrap(srrmlr_simu(train_X, train_Y, val_X, val_Y, test_X, test_Y, s_list, r_list, C_true, s_true, r_true));
    return rcpp_result_gen;
END_RCPP
}
// srrmlr_real
Rcpp::List srrmlr_real(arma::dmat& train_X, arma::dmat& train_Y, arma::dmat& test_X, arma::dmat& test_Y, arma::uvec& s_list, arma::uvec& r_list, arma::uword cv);
RcppExport SEXP _SRRMLR_srrmlr_real(SEXP train_XSEXP, SEXP train_YSEXP, SEXP test_XSEXP, SEXP test_YSEXP, SEXP s_listSEXP, SEXP r_listSEXP, SEXP cvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat& >::type train_X(train_XSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type train_Y(train_YSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type test_X(test_XSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type test_Y(test_YSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type s_list(s_listSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type r_list(r_listSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type cv(cvSEXP);
    rcpp_result_gen = Rcpp::wrap(srrmlr_real(train_X, train_Y, test_X, test_Y, s_list, r_list, cv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SRRMLR_srrmlr_one", (DL_FUNC) &_SRRMLR_srrmlr_one, 6},
    {"_SRRMLR_srrmlr_simu", (DL_FUNC) &_SRRMLR_srrmlr_simu, 11},
    {"_SRRMLR_srrmlr_real", (DL_FUNC) &_SRRMLR_srrmlr_real, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_SRRMLR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
