# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The base function of SRRMLR
#'
#' @param X the covariate matrix
#' @param Y the response matrix
#' @param s the sparsity
#' @param r the rank
#' @param e_in the stopping epsilon of inloop
#' @param e_out the stopping epsilon of outloop
#' @return C matrix aims to be solved
#' @return iters iterations taken when algorithm meet the stopping criterion 
#' @return Prob the probability matrix
#' @export 
#' @useDynLib SRRMLR
srrmlr_one <- function(X, Y, s, r, e_in = 0.001, e_out = 0.001) {
    .Call('_SRRMLR_srrmlr_one', PACKAGE = 'SRRMLR', X, Y, s, r, e_in, e_out)
}

#' SRRMLR in simulation analysis
#'
#' @param train_X the covariate matrix of training data
#' @param train_Y the response matrix of training data
#' @param val_X the covariate matrix of validation data
#' @param val_Y the response matrix of validation data
#' @param test_X the covariate matrix of test data
#' @param test_Y the response matrix of test data
#' @param s_list the list of sparsity
#' @param r_list the list of rank
#' @param C_true the true matrix C
#' @param s_true the true sparsity
#' @param r_true the true rank
#' @return Pred the predictive accuracy with the negative log-likelihood
#' @return Est the estimation accuracy
#' @return r rank selected by SRRMLR, the estimated rank
#' @return s sparsity selected by SRRMLR, also the number of non-zero rows in C_hat
#' @return Sen the sensitivity
#' @return Spe the specificity
#' @return time running time of the algorithm with selected rank and sparsity
#' @export 
#' @useDynLib SRRMLR
srrmlr_simu <- function(train_X, train_Y, val_X, val_Y, test_X, test_Y, s_list, r_list, C_true, s_true, r_true) {
    .Call('_SRRMLR_srrmlr_simu', PACKAGE = 'SRRMLR', train_X, train_Y, val_X, val_Y, test_X, test_Y, s_list, r_list, C_true, s_true, r_true)
}

#' SRRMLR in real data analysis
#'
#' @param train_X the covariate matrix of training data
#' @param train_Y the response matrix of training data
#' @param test_X the covariate matrix of test data
#' @param test_Y the response matrix of test data
#' @param s_list the list of sparsity
#' @param r_list the list of rank
#' @param cv the number of folds when conducting cross-validation, 5 in default
#' @return Pred the predictive accuracy with the negative log-likelihood
#' @return r rank selected by SRRMLR, the estimated rank
#' @return s sparsity selected by SRRMLR, also the number of non-zero rows in C_hat
#' @return A_set the index of features selected by SRRMLR.
#' @return time running time of the algorithm with selected rank and sparsity
#' @export 
#' @useDynLib SRRMLR
srrmlr_real <- function(train_X, train_Y, test_X, test_Y, s_list, r_list, cv = 5L) {
    .Call('_SRRMLR_srrmlr_real', PACKAGE = 'SRRMLR', train_X, train_Y, test_X, test_Y, s_list, r_list, cv)
}

